### ISSUE TITLE
Disconnected event not firing when network is disconnected

### ISSUE THREAD

**Issue by Julusian** [home-assistant/home-assistant-js-websocket#256]
I am using this library in nodejs, and all is fine except that it never notices disconnection.

I have been trying to look into how it works in the browser to replicate it, but have found that the example.html you provide doesn't notice either.

Very simple STR: 
* open the example.html page and authenticate to a server
* open the console, ready to view anything logged
* turn off wifi/networking on your computer
* wait a few minutes
* see that no disconnect has been logged

From more testing, I get the same behaviour in the home assistant ui. Turning off my laptop wifi and after a couple of minutes it doesn't report disconnection. But restart home-assistant and it notices within a couple of seconds.

As a final test, if I restart home-assistant with example.html open, it also reports disconnected.

I am guessing the difference is with restarting home-assistant the connection gets closed properly, and with cutting the network the client is sat waiting to receive some data

**Comment by balloob** [comment]
Yeah that's correct. You can add your own ping-based connection alive detection. In your code call `connection.ping()`. It returns a promise that resolves when you get a `pong` response from the server. If you don't get a response within X time, call `connection.reconnect(true)` to force a reconnect.

**Comment by Julusian** [comment]
Ah, I didnt think of using the ping function like that.

But this feels like something the library should handle internally.
The readme states:
> The connection object will automatically try to reconnect to the server when the connection gets lost

But that is only true if the connection gets lost in some ways. Remember that this also affects home-assistant itself, so I suspect that anyone viewing a dashboard on patchy wifi or other unreliable networks is likely to hit this bug

**Comment by balloob** [comment]
Building it into the lib is tricky. You probably would implement it then using `setTimeout` or `setInterval` so you can send a message 60 seconds after the last message comes in/goes out.

However in a browser `setTimeout` and `setInterval` are throttled and won't actually execute when you think it will, and even then the amount of time you get is limited. On top of that HA also will suspend a connection when tab is in background for X time. It gets complicated fast! 

So although it is probably good to have something in this lib, we should only offer hooks for people to be able to build this functionality on top and handle all their own edge cases themselves.

**Comment by RonnyWinkler** [comment]
Hi, I know that this issue a old, but I have a detail question about `connection.ping()`
You wrote this method is method resolves when the pong is received.
So if a `await connection.ping()` does not throw an error all is ok? And if no pong is received, the method rejects after a timeout?
I ask because the method resolves, but without a return parameter (pong response) if the connection is valid.
And my connection check doesn't throw an error if the HA was diconnected previously. 
In this case, the websocked connection seems to re-established only partially some times. That means entity state updates are transmitted from HA, but service calls to HA are not processed. I'm still investigating and would like to ensure using `connection.ping()` right.
Many thanks in advance
Ronny
